import app from "./entry-v25.js";

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/api/health"&&request.method==="GET")return handleHealth(request,env,ctx);if(url.pathname==="/api/build-v2"&&request.method==="POST")return handleBuildV251(request,env,ctx);return app.fetch(request,env,ctx)}};

async function handleHealth(request,env,ctx){const base=await app.fetch(request,env,ctx);const payload=await base.json().catch(()=>({}));return json({...payload,buildWebMode:"v2.5.1-spatial-evidence-guard + v2.5-spatial-engine + v2.4.1-motion-baseline + v2.3.3-visual-baseline + v2.2.1-geometry-baseline + v2.1.3-structure-baseline + v1-static-snapshot",structuralLockBaseline:"2.1.3",geometryLockBaseline:"2.2.1",visualLockBaseline:"2.3.3",motionLockBaseline:"2.4.1",structuralLockPreserved:true,geometryLockPreserved:true,visualLockPreserved:true,motionLockPreserved:true,spatialEvidenceGuard:true,spatialActivationConditional:true,spatialNoEvidenceMeansNeutral:true,spatialEvidenceUsesPublicMarkupOnly:true,spatialEvidenceExecutesTargetJavaScript:false,spatialCopiesTargetThreeJs:false,spatialCopiesTargetShaders:false,spatialUsesGeneratedCssOnly:true,spatialUsesGeneratedJsOnly:true,v25BaseEngine:"2.5.0",version:"2.5.1"},base.status)}

async function handleBuildV251(request,env,ctx){const started=Date.now();let targetUrl="";try{const body=await request.clone().json();targetUrl=String(body?.url||"").trim()}catch{}
 const [baseResponse,evidence]=await Promise.all([app.fetch(request,env,ctx),inspectSpatialEvidence(targetUrl)]);const contentType=baseResponse.headers.get("content-type")||"";if(!/application\/json/i.test(contentType))return baseResponse;const payload=await baseResponse.json().catch(()=>null);if(!payload||!baseResponse.ok||!payload.ok||!payload.html)return new Response(payload?JSON.stringify(payload):"{}",{status:baseResponse.status,headers:JSON_HEADERS});
 let html=String(payload.html||"");const activate=Boolean(evidence.available&&evidence.strongCount>0);if(!activate)html=neutralizeV25(html);html=stampV251(html,activate,evidence);html=html.replace(/Spatial Fidelity Reconstruction V2\.5/g,"Spatial Evidence Guard Reconstruction V2.5.1").replace(/Structure, geometry, visual and motion-locked reconstruction with generated spatial depth fidelity and accessibility guards\./g,activate?"Structure, geometry, visual and motion-locked reconstruction with evidence-gated generated spatial depth.":"Structure, geometry, visual and motion-locked reconstruction with spatial effects held neutral because public source evidence was insufficient.");
 const baselineReady=Boolean(payload.stats?.structuralLockReady&&payload.stats?.geometryLockReady&&payload.stats?.visualBaselinePreserved&&payload.stats?.motionBaselinePreserved);const spatialCssRetained=html.includes("pfr-v25-spatial-css");const spatialJsRetained=html.includes("pfr-v25-spatial-js");const guardReady=Boolean(baselineReady&&((activate&&spatialCssRetained&&spatialJsRetained)||(!activate&&!spatialCssRetained&&!spatialJsRetained)));
 return json({...payload,engine:"v2.5.1-spatial-evidence-guard",mode:"clean-reconstruction-v251",filename:String(payload.filename||"clean-v25.html").replace(/-clean-v25\.html$/i,"-clean-v251.html").replace(/-clean-v241\.html$/i,"-clean-v251.html"),html,htmlBytes:byteLength(html),durationMs:Date.now()-started,stats:{...(payload.stats||{}),structuralLockPreserved:Boolean(payload.stats?.structuralLockReady),geometryLockPreserved:Boolean(payload.stats?.geometryLockReady),visualBaselinePreserved:Boolean(payload.stats?.visualBaselinePreserved),motionBaselinePreserved:Boolean(payload.stats?.motionBaselinePreserved),spatialEvidenceGuardApplied:guardReady,spatialEvidenceAvailable:evidence.available,spatialEvidenceStrongSignals:evidence.strongCount,spatialEvidenceWeakSignals:evidence.weakCount,spatialEvidenceSignals:evidence.signals,spatialEffectsActivated:activate,spatialNeutralMode:!activate,spatialCssApplied:spatialCssRetained,spatialJsApplied:spatialJsRetained,spatialBaselineCandidateReady:guardReady,targetScriptsCopied:0,targetLayoutCssCopied:0,targetFontFilesCopied:0},model:{...(payload.model||{}),spatialEvidenceGuard:{version:"2.5.1",base:"2.5.0",activationThresholdStrongSignals:1,evidenceAvailable:evidence.available,strongSignals:evidence.strongCount,weakSignals:evidence.weakCount,signals:evidence.signals,mode:activate?"evidence-active":"neutral",generatedCssOnly:true,generatedJsOnly:true}},safety:{...(payload.safety||{}),targetScriptsCopied:false,targetJavaScriptExecutedByBuild:false,targetCssUsedAsLayoutFoundation:false,targetCssCopied:false,targetFontFilesCopied:false,spatialEvidenceUsesPublicMarkupOnly:true,spatialEvidenceExecutesTargetJavaScript:false,spatialCopiesTargetThreeJs:false,spatialCopiesTargetShaders:false,spatialEffectsRequireEvidence:true,spatialNeutralWithoutEvidence:true}},baseResponse.status)}

async function inspectSpatialEvidence(rawUrl){if(!rawUrl||!isSafePublicUrl(rawUrl))return{available:false,strongCount:0,weakCount:0,signals:[]};try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);const res=await fetch(rawUrl,{method:"GET",redirect:"manual",headers:{accept:"text/html,application/xhtml+xml","user-agent":"Passive-Fetch-Render-Auditor/2.5.1 Spatial-Evidence-Guard"},signal:controller.signal});clearTimeout(timer);if(res.status<200||res.status>=300)return{available:false,strongCount:0,weakCount:0,signals:[]};const text=(await res.text()).slice(0,2500000);const tests=[[/\bperspective\s*:/i,"css-perspective"],[/\btranslateZ\s*\(/i,"translateZ"],[/\brotateX\s*\(/i,"rotateX"],[/\brotateY\s*\(/i,"rotateY"],[/\bwebgl2?\b/i,"webgl"],[/\bthree(?:\.min)?\.js\b|\bTHREE\./i,"threejs"],[/<model-viewer\b/i,"model-viewer"],[/\b(?:vertex|fragment)\s+shader\b|\bgl_FragColor\b|\bgl_Position\b/i,"shader"]];const signals=[];for(const [re,name] of tests)if(re.test(text))signals.push(name);const weak=[];if(/<canvas\b/i.test(text))weak.push("canvas");return{available:true,strongCount:signals.length,weakCount:weak.length,signals:[...signals,...weak]}}catch{return{available:false,strongCount:0,weakCount:0,signals:[]}}}

function neutralizeV25(html){return String(html||"").replace(/<style\b[^>]*id=["']pfr-v25-spatial-css["'][^>]*>[\s\S]*?<\/style\s*>/i,"").replace(/<script\b[^>]*id=["']pfr-v25-spatial-js["'][^>]*>[\s\S]*?<\/script\s*>/i,"")}
function stampV251(html,active,evidence){return String(html||"").replace(/<html\b([^>]*)>/i,(all,attrs)=>{let next=String(attrs||"").replace(/\sdata-spatial-evidence=(['"])[^'"]*\1/ig,"").replace(/\sdata-spatial-mode=(['"])[^'"]*\1/ig,"").replace(/\sdata-spatial-guard=(['"])[^'"]*\1/ig,"");return `<html${next} data-spatial-guard="v2.5.1" data-spatial-evidence="${evidence.strongCount}" data-spatial-mode="${active?"active":"neutral"}">`})}
function isSafePublicUrl(value){try{const u=new URL(value);if(!/^https?:$/.test(u.protocol)||u.username||u.password)return false;const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,"");if(h==="localhost"||h.endsWith(".localhost")||h.endsWith(".local")||h.endsWith(".internal"))return false;if(/^127\.|^10\.|^192\.168\.|^169\.254\./.test(h))return false;const m=h.match(/^172\.(\d+)\./);if(m&&Number(m[1])>=16&&Number(m[1])<=31)return false;if(h==="::1"||h.startsWith("fc")||h.startsWith("fd")||h.startsWith("fe80:"))return false;return true}catch{return false}}
function byteLength(value){return new TextEncoder().encode(String(value||"")).length}function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:JSON_HEADERS})}
