import app from "./entry-v261.js";

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/api/health"&&request.method==="GET")return handleHealth(request,env,ctx);if(url.pathname==="/api/build-v2"&&request.method==="POST")return handleBuildV262(request,env,ctx);return app.fetch(request,env,ctx)}};

async function handleHealth(request,env,ctx){const base=await app.fetch(request,env,ctx);const payload=await base.json().catch(()=>({}));return json({...payload,buildWebMode:"v2.6.2-nested-escape-guard + v2.6.1-focus-return-finalizer + v2.6-interaction-fidelity + v2.5.1-spatial-baseline + v2.4.1-motion-baseline + v2.3.3-visual-baseline + v2.2.1-geometry-baseline + v2.1.3-structure-baseline + v1-static-snapshot",structuralLockBaseline:"2.1.3",geometryLockBaseline:"2.2.1",visualLockBaseline:"2.3.3",motionLockBaseline:"2.4.1",spatialLockBaseline:"2.5.1",structuralLockPreserved:true,geometryLockPreserved:true,visualLockPreserved:true,motionLockPreserved:true,spatialLockPreserved:true,interactionNestedEscapeGuard:true,nestedEscapeSingleLayer:true,submenuEscapePriority:true,journeysEscapePriority:true,menuEscapeFallback:true,contextualFocusReturn:true,interactionUsesGeneratedJsOnly:true,interactionCopiesTargetJavaScript:false,v261BaseEngine:"2.6.1",version:"2.6.2"},base.status)}

async function handleBuildV262(request,env,ctx){const started=Date.now();const baseResponse=await app.fetch(request,env,ctx);const contentType=baseResponse.headers.get("content-type")||"";if(!/application\/json/i.test(contentType))return baseResponse;const payload=await baseResponse.json().catch(()=>null);if(!payload||!baseResponse.ok||!payload.ok||!payload.html)return new Response(payload?JSON.stringify(payload):"{}",{status:baseResponse.status,headers:JSON_HEADERS});let html=String(payload.html||"");html=stampV262(html);html=replaceFocusReturnJs(html);html=html.replace(/Focus Return Finalizer Reconstruction V2\.6\.1/g,"Nested Escape Guard Reconstruction V2.6.2").replace(/Structure, geometry, visual, motion and spatial-locked reconstruction with finalized contextual keyboard focus return\./g,"Structure, geometry, visual, motion and spatial-locked reconstruction with single-layer nested Escape handling and contextual focus return.");const jsApplied=html.includes("pfr-v262-nested-escape-js");const oldJsRemoved=!html.includes("pfr-v261-focus-return-js")&&!html.includes("pfr-v26-interaction-js");const baselineReady=Boolean(payload.stats?.structuralLockReady&&payload.stats?.geometryLockReady&&payload.stats?.visualBaselinePreserved&&payload.stats?.motionBaselinePreserved&&payload.stats?.spatialBaselinePreserved);const ready=Boolean(jsApplied&&oldJsRemoved&&baselineReady);return json({...payload,engine:"v2.6.2-nested-escape-guard",mode:"clean-reconstruction-v262",filename:String(payload.filename||"clean-v261.html").replace(/-clean-v261\.html$/i,"-clean-v262.html"),html,htmlBytes:byteLength(html),durationMs:Date.now()-started,stats:{...(payload.stats||{}),structuralLockPreserved:Boolean(payload.stats?.structuralLockReady),geometryLockPreserved:Boolean(payload.stats?.geometryLockReady),visualBaselinePreserved:Boolean(payload.stats?.visualBaselinePreserved),motionBaselinePreserved:Boolean(payload.stats?.motionBaselinePreserved),spatialBaselinePreserved:Boolean(payload.stats?.spatialBaselinePreserved),interactionFidelityEngineApplied:Boolean(payload.stats?.interactionFidelityEngineApplied),nestedEscapeGuardApplied:ready,nestedEscapeSingleLayerApplied:ready,submenuEscapePriorityApplied:ready,journeysEscapePriorityApplied:ready,menuEscapeFallbackApplied:ready,contextualFocusReturnApplied:ready,legacyFocusReturnJsRemoved:oldJsRemoved,interactionBaselineCandidateReady:ready,targetScriptsCopied:0,targetLayoutCssCopied:0,targetFontFilesCopied:0},model:{...(payload.model||{}),interactionNestedEscape:{version:"2.6.2",base:"2.6.1",order:["submenu","journeys","menu"],singleLayerPerEscape:true,contextualFocusReturn:true,generatedJsOnly:true}},safety:{...(payload.safety||{}),targetScriptsCopied:false,targetJavaScriptExecutedByBuild:false,targetCssUsedAsLayoutFoundation:false,targetCssCopied:false,targetFontFilesCopied:false,interactionUsesGeneratedJsOnly:true,interactionExecutesTargetJavaScript:false,interactionSubmitsTargetForms:false}},baseResponse.status)}

function stampV262(html){return String(html||"").replace(/<html\b([^>]*)>/i,(all,attrs)=>{let next=String(attrs||"").replace(/\sdata-interaction-guard=(['"])[^'"]*\1/i,"");return `<html${next} data-interaction-guard="v2.6.2">`})}

function replaceFocusReturnJs(html){const source=String(html||"");const js=`<script id="pfr-v262-nested-escape-js">(()=>{const d=document.documentElement,menu=document.querySelector('#menuOverlay'),menuToggle=document.querySelector('#menuToggle'),journeys=document.querySelector('#journeys'),journeysBtn=journeys?.querySelector('.journeys-btn'),rows=[...document.querySelectorAll('[data-menu-row]')];const sync=()=>{if(menu)menu.dataset.interactionState=menu.classList.contains('open')?'open':'closed';if(journeys)journeys.dataset.interactionState=journeys.classList.contains('open')?'open':'closed';for(const row of rows)row.dataset.interactionState=row.classList.contains('open')?'open':'closed'};const focus=(el)=>{sync();el?.focus({preventScroll:true})};sync();for(const node of [menu,journeys,...rows])if(node)new MutationObserver(sync).observe(node,{attributes:true,attributeFilter:['class']});addEventListener('keydown',e=>{d.dataset.inputModality='keyboard';if(e.key!=='Escape')return;const openRow=rows.find(row=>row.classList.contains('open'));if(openRow){const trigger=openRow.querySelector('.menu-submenu-toggle');openRow.classList.remove('open');trigger?.setAttribute('aria-expanded','false');focus(trigger);return}if(journeys?.classList.contains('open')){journeys.classList.remove('open');journeysBtn?.setAttribute('aria-expanded','false');focus(journeysBtn);return}if(menu?.classList.contains('open')){menu.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false');focus(menuToggle);return}});addEventListener('pointerdown',()=>{d.dataset.inputModality='pointer'},{passive:true});document.addEventListener('click',sync);})();</script>`;if(/<script\b[^>]*id=["']pfr-v261-focus-return-js["'][^>]*>[\s\S]*?<\/script\s*>/i.test(source))return source.replace(/<script\b[^>]*id=["']pfr-v261-focus-return-js["'][^>]*>[\s\S]*?<\/script\s*>/i,js);if(/<script\b[^>]*id=["']pfr-v26-interaction-js["'][^>]*>[\s\S]*?<\/script\s*>/i.test(source))return source.replace(/<script\b[^>]*id=["']pfr-v26-interaction-js["'][^>]*>[\s\S]*?<\/script\s*>/i,js);return source.replace(/<\/body\s*>/i,`${js}</body>`)}

function byteLength(value){return new TextEncoder().encode(String(value||"")).length}function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:JSON_HEADERS})}
