import app from "./entry-v27.js";

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/api/health"&&request.method==="GET")return handleHealth(request,env,ctx);if(url.pathname==="/api/build-v2"&&request.method==="POST")return handleBuildV28(request,env,ctx);return app.fetch(request,env,ctx)}};

async function handleHealth(request,env,ctx){const base=await app.fetch(request,env,ctx);const payload=await base.json().catch(()=>({}));return json({...payload,buildWebMode:"v2.8-responsive-viewport-guard + v2.7-accessibility-fidelity + v2.6.2-interaction-baseline + v2.5.1-spatial-baseline + v2.4.1-motion-baseline + v2.3.3-visual-baseline + v2.2.1-geometry-baseline + v2.1.3-structure-baseline + v1-static-snapshot",structuralLockBaseline:"2.1.3",geometryLockBaseline:"2.2.1",visualLockBaseline:"2.3.3",motionLockBaseline:"2.4.1",spatialLockBaseline:"2.5.1",interactionLockBaseline:"2.6.2",responsiveViewportGuard:true,viewportBandInstrumentation:true,visualViewportInstrumentation:true,safeAreaHardening:true,horizontalOverflowGuard:true,lockedGeometryOverridden:false,responsiveUsesGeneratedCssOnly:true,responsiveUsesGeneratedJsOnly:true,responsiveCopiesTargetJavaScript:false,v27BaseEngine:"2.7.0",version:"2.8.0"},base.status)}

async function handleBuildV28(request,env,ctx){const started=Date.now();const baseResponse=await app.fetch(request,env,ctx);const contentType=baseResponse.headers.get("content-type")||"";if(!/application\/json/i.test(contentType))return baseResponse;const payload=await baseResponse.json().catch(()=>null);if(!payload||!baseResponse.ok||!payload.ok||!payload.html)return new Response(payload?JSON.stringify(payload):"{}",{status:baseResponse.status,headers:JSON_HEADERS});let html=String(payload.html||"");html=stampV28(html);html=injectViewportCss(html);html=injectViewportJs(html);html=html.replace(/Accessibility Fidelity Reconstruction V2\.7/g,"Responsive / Viewport Fidelity Guard V2.8").replace(/Structure, geometry, visual, motion, spatial and interaction-locked reconstruction with generated accessibility semantics and ARIA state synchronization\./g,"Structure, geometry, visual, motion, spatial and interaction-locked reconstruction with generated accessibility semantics plus responsive viewport integrity guards.");const cssApplied=html.includes("pfr-v28-viewport-css");const jsApplied=html.includes("pfr-v28-viewport-js");const geometryPreserved=Boolean(payload.stats?.geometryLockReady||payload.stats?.geometryLockPreserved);const baselineReady=Boolean(payload.stats?.structuralLockReady&&geometryPreserved&&payload.stats?.visualBaselinePreserved&&payload.stats?.motionBaselinePreserved&&payload.stats?.spatialBaselinePreserved&&payload.stats?.interactionBaselinePreserved);const ready=Boolean(cssApplied&&jsApplied&&baselineReady);return json({...payload,engine:"v2.8-responsive-viewport-fidelity-guard",mode:"clean-reconstruction-v28",filename:String(payload.filename||"clean-v27.html").replace(/-clean-v27\.html$/i,"-clean-v28.html"),html,htmlBytes:byteLength(html),durationMs:Date.now()-started,stats:{...(payload.stats||{}),responsiveViewportGuardApplied:ready,viewportBandInstrumentationApplied:jsApplied,visualViewportInstrumentationApplied:jsApplied,safeAreaHardeningApplied:cssApplied,horizontalOverflowGuardApplied:cssApplied,lockedGeometryOverridden:false,responsiveBaselineCandidateReady:ready,targetScriptsCopied:0,targetLayoutCssCopied:0,targetFontFilesCopied:0},model:{...(payload.model||{}),responsiveViewportGuard:{version:"2.8.0",base:"2.7.0",bands:{mobile:"<=600",tablet:"601-992",desktop:">992"},visualViewport:true,safeArea:true,horizontalOverflowGuard:true,lockedGeometryOverridden:false,generatedCssOnly:true,generatedJsOnly:true}},safety:{...(payload.safety||{}),targetScriptsCopied:false,targetJavaScriptExecutedByBuild:false,targetCssUsedAsLayoutFoundation:false,targetCssCopied:false,targetFontFilesCopied:false,responsiveUsesGeneratedCssOnly:true,responsiveUsesGeneratedJsOnly:true,responsiveExecutesTargetJavaScript:false,responsiveOverridesLockedGeometry:false}},baseResponse.status)}

function stampV28(html){return String(html||"").replace(/<html\b([^>]*)>/i,(all,attrs)=>{let next=String(attrs||"").replace(/\sdata-responsive-engine=(['"])[^'"]*\1/i,"");return `<html${next} data-responsive-engine="v2.8">`})}

function injectViewportCss(html){const source=String(html||"");if(source.includes("pfr-v28-viewport-css"))return source;const css=`<style id="pfr-v28-viewport-css">
/* V2.8 — generated viewport integrity guard. Locked geometry tokens are not replaced. */
html[data-responsive-engine="v2.8"],html[data-responsive-engine="v2.8"] body{max-width:100%;overflow-x:clip}
html[data-responsive-engine="v2.8"] :is(img,svg,video,canvas){max-width:100%}
html[data-responsive-engine="v2.8"] .topbar{padding-left:max(var(--geo-side,40px),env(safe-area-inset-left));padding-right:max(var(--geo-side,40px),env(safe-area-inset-right))}
html[data-responsive-engine="v2.8"] .menu-overlay{padding-bottom:max(60px,env(safe-area-inset-bottom))}
html[data-responsive-engine="v2.8"] .journeys{max-width:calc(100vw - max(24px,env(safe-area-inset-left)) - max(24px,env(safe-area-inset-right)))}
html[data-responsive-engine="v2.8"] .journeys-menu{max-width:calc(100vw - 24px);overflow-x:auto;overscroll-behavior-inline:contain}
html[data-responsive-engine="v2.8"] [data-viewport-overflow="true"] .pfr-skip-link{max-width:calc(100vw - 32px)}
@media(max-width:992px){html[data-responsive-engine="v2.8"] .menu-overlay{overscroll-behavior:contain}}
@media(max-width:600px){html[data-responsive-engine="v2.8"] .topbar{padding-left:max(20px,env(safe-area-inset-left));padding-right:max(20px,env(safe-area-inset-right))}html[data-responsive-engine="v2.8"] .journeys{bottom:max(28px,env(safe-area-inset-bottom))}}
</style>`;return /<\/head\s*>/i.test(source)?source.replace(/<\/head\s*>/i,`${css}</head>`):css+source}

function injectViewportJs(html){const source=String(html||"");if(source.includes("pfr-v28-viewport-js"))return source;const js=`<script id="pfr-v28-viewport-js">(()=>{const d=document.documentElement;if(d.dataset.viewportGuardInit==='1')return;d.dataset.viewportGuardInit='1';let raf=0;const sync=()=>{raf=0;const vv=window.visualViewport,w=Math.round(vv?.width||innerWidth),h=Math.round(vv?.height||innerHeight);d.style.setProperty('--pfr-vw',w+'px');d.style.setProperty('--pfr-vh',h+'px');d.dataset.viewportBand=w<=600?'mobile':w<=992?'tablet':'desktop';d.dataset.viewportOrientation=w>=h?'landscape':'portrait';const sw=Math.max(d.scrollWidth,document.body?.scrollWidth||0);d.dataset.viewportOverflow=sw>w+2?'true':'false'};const schedule=()=>{if(!raf)raf=requestAnimationFrame(sync)};addEventListener('resize',schedule,{passive:true});addEventListener('orientationchange',schedule,{passive:true});visualViewport?.addEventListener('resize',schedule,{passive:true});visualViewport?.addEventListener('scroll',schedule,{passive:true});sync()})();</script>`;return source.replace(/<\/body\s*>/i,`${js}</body>`)}

function byteLength(value){return new TextEncoder().encode(String(value||"")).length}
function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:JSON_HEADERS})}
