import app from "./entry-v26.js";

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/api/health"&&request.method==="GET")return handleHealth(request,env,ctx);if(url.pathname==="/api/build-v2"&&request.method==="POST")return handleBuildV261(request,env,ctx);return app.fetch(request,env,ctx)}};

async function handleHealth(request,env,ctx){const base=await app.fetch(request,env,ctx);const payload=await base.json().catch(()=>({}));return json({...payload,buildWebMode:"v2.6.1-focus-return-finalizer + v2.6-interaction-fidelity + v2.5.1-spatial-baseline + v2.4.1-motion-baseline + v2.3.3-visual-baseline + v2.2.1-geometry-baseline + v2.1.3-structure-baseline + v1-static-snapshot",structuralLockBaseline:"2.1.3",geometryLockBaseline:"2.2.1",visualLockBaseline:"2.3.3",motionLockBaseline:"2.4.1",spatialLockBaseline:"2.5.1",structuralLockPreserved:true,geometryLockPreserved:true,visualLockPreserved:true,motionLockPreserved:true,spatialLockPreserved:true,interactionFocusReturnFinalizer:true,contextualFocusReturn:true,menuFocusReturn:true,journeysFocusReturn:true,submenuFocusReturn:true,interactionUsesGeneratedJsOnly:true,interactionCopiesTargetJavaScript:false,v26BaseEngine:"2.6.0",version:"2.6.1"},base.status)}

async function handleBuildV261(request,env,ctx){const started=Date.now();const baseResponse=await app.fetch(request,env,ctx);const contentType=baseResponse.headers.get("content-type")||"";if(!/application\/json/i.test(contentType))return baseResponse;const payload=await baseResponse.json().catch(()=>null);if(!payload||!baseResponse.ok||!payload.ok||!payload.html)return new Response(payload?JSON.stringify(payload):"{}",{status:baseResponse.status,headers:JSON_HEADERS});
 let html=String(payload.html||"");html=stampV261(html);html=replaceInteractionJs(html);html=html.replace(/Interaction Fidelity Reconstruction V2\.6/g,"Focus Return Finalizer Reconstruction V2.6.1").replace(/Structure, geometry, visual, motion and spatial-locked reconstruction with generated interaction-state fidelity\./g,"Structure, geometry, visual, motion and spatial-locked reconstruction with finalized contextual keyboard focus return.");
 const jsApplied=html.includes("pfr-v261-focus-return-js");const oldJsRemoved=!html.includes("pfr-v26-interaction-js");const baselineReady=Boolean(payload.stats?.structuralLockReady&&payload.stats?.geometryLockReady&&payload.stats?.visualBaselinePreserved&&payload.stats?.motionBaselinePreserved&&payload.stats?.spatialBaselinePreserved);const ready=Boolean(jsApplied&&oldJsRemoved&&baselineReady);
 return json({...payload,engine:"v2.6.1-focus-return-finalizer",mode:"clean-reconstruction-v261",filename:String(payload.filename||"clean-v26.html").replace(/-clean-v26\.html$/i,"-clean-v261.html"),html,htmlBytes:byteLength(html),durationMs:Date.now()-started,stats:{...(payload.stats||{}),structuralLockPreserved:Boolean(payload.stats?.structuralLockReady),geometryLockPreserved:Boolean(payload.stats?.geometryLockReady),visualBaselinePreserved:Boolean(payload.stats?.visualBaselinePreserved),motionBaselinePreserved:Boolean(payload.stats?.motionBaselinePreserved),spatialBaselinePreserved:Boolean(payload.stats?.spatialBaselinePreserved),interactionFidelityEngineApplied:Boolean(payload.stats?.interactionFidelityEngineApplied),focusReturnFinalizerApplied:ready,contextualFocusReturnApplied:ready,menuFocusReturnApplied:ready,journeysFocusReturnApplied:ready,submenuFocusReturnApplied:ready,legacyInteractionJsRemoved:oldJsRemoved,interactionBaselineCandidateReady:ready,targetScriptsCopied:0,targetLayoutCssCopied:0,targetFontFilesCopied:0},model:{...(payload.model||{}),interactionFocusReturn:{version:"2.6.1",base:"2.6.0",menuTrigger:"menuToggle",journeysTrigger:"journeysBtn",submenuTrigger:"row-local submenu toggle",contextual:true,generatedJsOnly:true}},safety:{...(payload.safety||{}),targetScriptsCopied:false,targetJavaScriptExecutedByBuild:false,targetCssUsedAsLayoutFoundation:false,targetCssCopied:false,targetFontFilesCopied:false,interactionUsesGeneratedJsOnly:true,interactionExecutesTargetJavaScript:false,interactionSubmitsTargetForms:false}},baseResponse.status)}

function stampV261(html){return String(html||"").replace(/<html\b([^>]*)>/i,(all,attrs)=>{let next=String(attrs||"").replace(/\sdata-interaction-guard=(['"])[^'"]*\1/i,"");return `<html${next} data-interaction-guard="v2.6.1">`})}

function replaceInteractionJs(html){const source=String(html||"");const js=`<script id="pfr-v261-focus-return-js">(()=>{const d=document.documentElement,menu=document.querySelector('#menuOverlay'),menuToggle=document.querySelector('#menuToggle'),journeys=document.querySelector('#journeys'),journeysBtn=journeys?.querySelector('.journeys-btn'),rows=[...document.querySelectorAll('[data-menu-row]')];const sync=()=>{if(menu)menu.dataset.interactionState=menu.classList.contains('open')?'open':'closed';if(journeys)journeys.dataset.interactionState=journeys.classList.contains('open')?'open':'closed';for(const row of rows)row.dataset.interactionState=row.classList.contains('open')?'open':'closed'};sync();for(const node of [menu,journeys,...rows])if(node)new MutationObserver(sync).observe(node,{attributes:true,attributeFilter:['class']});addEventListener('keydown',e=>{d.dataset.inputModality='keyboard';if(e.key!=='Escape')return;let returnTarget=null;for(const row of rows){if(!row.classList.contains('open'))continue;const trigger=row.querySelector('.menu-submenu-toggle');row.classList.remove('open');trigger?.setAttribute('aria-expanded','false');if(!returnTarget)returnTarget=trigger}if(journeys?.classList.contains('open')){journeys.classList.remove('open');journeysBtn?.setAttribute('aria-expanded','false');if(!returnTarget)returnTarget=journeysBtn}if(menu?.classList.contains('open')){menu.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false');if(!returnTarget)returnTarget=menuToggle}if(returnTarget){sync();returnTarget.focus({preventScroll:true})}});addEventListener('pointerdown',()=>{d.dataset.inputModality='pointer'},{passive:true});document.addEventListener('click',sync);})();</script>`;if(/<script\b[^>]*id=["']pfr-v26-interaction-js["'][^>]*>[\s\S]*?<\/script\s*>/i.test(source))return source.replace(/<script\b[^>]*id=["']pfr-v26-interaction-js["'][^>]*>[\s\S]*?<\/script\s*>/i,js);return source.replace(/<\/body\s*>/i,`${js}</body>`)}

function byteLength(value){return new TextEncoder().encode(String(value||"")).length}function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:JSON_HEADERS})}
