import app from "./entry-v251.js";

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==="/api/health"&&request.method==="GET")return handleHealth(request,env,ctx);if(url.pathname==="/api/build-v2"&&request.method==="POST")return handleBuildV26(request,env,ctx);return app.fetch(request,env,ctx)}};

async function handleHealth(request,env,ctx){const base=await app.fetch(request,env,ctx);const payload=await base.json().catch(()=>({}));return json({...payload,buildWebMode:"v2.6-interaction-fidelity + v2.5.1-spatial-baseline + v2.4.1-motion-baseline + v2.3.3-visual-baseline + v2.2.1-geometry-baseline + v2.1.3-structure-baseline + v1-static-snapshot",structuralLockBaseline:"2.1.3",geometryLockBaseline:"2.2.1",visualLockBaseline:"2.3.3",motionLockBaseline:"2.4.1",spatialLockBaseline:"2.5.1",structuralLockPreserved:true,geometryLockPreserved:true,visualLockPreserved:true,motionLockPreserved:true,spatialLockPreserved:true,interactionFidelityEngine:true,focusVisiblePolish:true,pressedStateFeedback:true,keyboardEscapeHandling:true,menuStateSynchronization:true,inputModalityTracking:true,interactionUsesGeneratedCssOnly:true,interactionUsesGeneratedJsOnly:true,interactionCopiesTargetJavaScript:false,v251BaseEngine:"2.5.1",version:"2.6.0"},base.status)}

async function handleBuildV26(request,env,ctx){const started=Date.now();const baseResponse=await app.fetch(request,env,ctx);const contentType=baseResponse.headers.get("content-type")||"";if(!/application\/json/i.test(contentType))return baseResponse;const payload=await baseResponse.json().catch(()=>null);if(!payload||!baseResponse.ok||!payload.ok||!payload.html)return new Response(payload?JSON.stringify(payload):"{}",{status:baseResponse.status,headers:JSON_HEADERS});
 let html=String(payload.html||"");html=stampV26(html);html=injectInteractionCss(html);html=injectInteractionJs(html);html=html.replace(/Spatial Evidence Guard Reconstruction V2\.5\.1/g,"Interaction Fidelity Reconstruction V2.6").replace(/Structure, geometry, visual and motion-locked reconstruction with spatial effects held neutral because public source evidence was insufficient\./g,"Structure, geometry, visual, motion and spatial-locked reconstruction with generated interaction-state fidelity.").replace(/Structure, geometry, visual and motion-locked reconstruction with evidence-gated generated spatial depth\./g,"Structure, geometry, visual, motion and spatial-locked reconstruction with generated interaction-state fidelity.");
 const cssApplied=html.includes("pfr-v26-interaction-css"),jsApplied=html.includes("pfr-v26-interaction-js");const baselineReady=Boolean(payload.stats?.structuralLockReady&&payload.stats?.geometryLockReady&&payload.stats?.visualBaselinePreserved&&payload.stats?.motionBaselinePreserved&&payload.stats?.spatialBaselineCandidateReady);const ready=Boolean(cssApplied&&jsApplied&&baselineReady);
 return json({...payload,engine:"v2.6-interaction-fidelity-engine",mode:"clean-reconstruction-v26",filename:String(payload.filename||"clean-v251.html").replace(/-clean-v251\.html$/i,"-clean-v26.html"),html,htmlBytes:byteLength(html),durationMs:Date.now()-started,stats:{...(payload.stats||{}),structuralLockPreserved:Boolean(payload.stats?.structuralLockReady),geometryLockPreserved:Boolean(payload.stats?.geometryLockReady),visualBaselinePreserved:Boolean(payload.stats?.visualBaselinePreserved),motionBaselinePreserved:Boolean(payload.stats?.motionBaselinePreserved),spatialBaselinePreserved:Boolean(payload.stats?.spatialBaselineCandidateReady),interactionFidelityEngineApplied:ready,interactionCssApplied:cssApplied,interactionJsApplied:jsApplied,focusVisiblePolishApplied:cssApplied,pressedStateFeedbackApplied:cssApplied,keyboardEscapeHandlingApplied:jsApplied,menuStateSynchronizationApplied:jsApplied,inputModalityTrackingApplied:jsApplied,interactionBaselineCandidateReady:ready,targetScriptsCopied:0,targetLayoutCssCopied:0,targetFontFilesCopied:0},model:{...(payload.model||{}),interactionFidelity:{version:"2.6.0",base:"2.5.1",focusVisible:true,pressedState:true,escapeHandling:true,menuStateSync:true,inputModality:true,generatedCssOnly:true,generatedJsOnly:true}},safety:{...(payload.safety||{}),targetScriptsCopied:false,targetJavaScriptExecutedByBuild:false,targetCssUsedAsLayoutFoundation:false,targetCssCopied:false,targetFontFilesCopied:false,interactionUsesGeneratedCssOnly:true,interactionUsesGeneratedJsOnly:true,interactionExecutesTargetJavaScript:false,interactionSubmitsTargetForms:false,interactionPreservesLockedStructure:Boolean(payload.stats?.structuralLockReady),interactionPreservesLockedGeometry:Boolean(payload.stats?.geometryLockReady),interactionPreservesLockedVisualBaseline:Boolean(payload.stats?.visualBaselinePreserved),interactionPreservesLockedMotionBaseline:Boolean(payload.stats?.motionBaselinePreserved),interactionPreservesLockedSpatialBaseline:Boolean(payload.stats?.spatialBaselineCandidateReady)}},baseResponse.status)}

function stampV26(html){return String(html||"").replace(/<html\b([^>]*)>/i,(all,attrs)=>{let next=String(attrs||"").replace(/\sdata-interaction-engine=(['"])[^'"]*\1/i,"");return `<html${next} data-interaction-engine="v2.6">`})}
function injectInteractionCss(html){const source=String(html||"");if(source.includes("pfr-v26-interaction-css"))return source;const css=`<style id="pfr-v26-interaction-css">
/* V2.6 — generated interaction fidelity. No target JavaScript. */
html[data-interaction-engine="v2.6"]{--interaction-ring:0 0 0 3px rgba(23,26,72,.22);--interaction-ring-light:0 0 0 3px rgba(255,255,255,.38)}
html[data-interaction-engine="v2.6"] :is(a,button,[tabindex]):focus{outline:none}
html[data-interaction-engine="v2.6"] :is(a,button,[tabindex]):focus-visible{outline:2px solid currentColor;outline-offset:4px;box-shadow:var(--interaction-ring);border-radius:inherit}
html[data-interaction-engine="v2.6"] .hero :is(a,button):focus-visible,html[data-interaction-engine="v2.6"] .moments-composite :is(a,button):focus-visible{box-shadow:var(--interaction-ring-light)}
html[data-interaction-engine="v2.6"] :is(.pill,.journeys-btn,.menu-toggle,.language,.menu-submenu-toggle,.encounter-arrow):active{transform:scale(.97)}
html[data-interaction-engine="v2.6"] .menu-row[data-interaction-state="open"]>.menu-main-label,html[data-interaction-engine="v2.6"] .menu-row[data-interaction-state="open"]>.menu-main-link{opacity:1}
html[data-interaction-engine="v2.6"][data-input-modality="keyboard"] :is(.menu-main-link,.menu-main-label,.menu-sub-link,.menu-blog-card,.menu-journey-card){text-underline-offset:.18em}
@media(prefers-reduced-motion:reduce){html[data-interaction-engine="v2.6"] :is(.pill,.journeys-btn,.menu-toggle,.language,.menu-submenu-toggle,.encounter-arrow):active{transform:none}}
</style>`;return /<\/head\s*>/i.test(source)?source.replace(/<\/head\s*>/i,`${css}</head>`):css+source}
function injectInteractionJs(html){const source=String(html||"");if(source.includes("pfr-v26-interaction-js"))return source;const js=`<script id="pfr-v26-interaction-js">(()=>{const d=document.documentElement,menu=document.querySelector('#menuOverlay'),menuToggle=document.querySelector('#menuToggle'),journeys=document.querySelector('#journeys'),journeysBtn=journeys?.querySelector('.journeys-btn'),rows=[...document.querySelectorAll('[data-menu-row]')];const sync=()=>{if(menu)menu.dataset.interactionState=menu.classList.contains('open')?'open':'closed';if(journeys)journeys.dataset.interactionState=journeys.classList.contains('open')?'open':'closed';for(const row of rows)row.dataset.interactionState=row.classList.contains('open')?'open':'closed'};sync();for(const node of [menu,journeys,...rows])if(node)new MutationObserver(sync).observe(node,{attributes:true,attributeFilter:['class']});addEventListener('keydown',e=>{d.dataset.inputModality='keyboard';if(e.key!=='Escape')return;let changed=false;if(menu?.classList.contains('open')){menu.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false');changed=true}if(journeys?.classList.contains('open')){journeys.classList.remove('open');journeysBtn?.setAttribute('aria-expanded','false');changed=true}for(const row of rows)if(row.classList.contains('open')){row.classList.remove('open');row.querySelector('.menu-submenu-toggle')?.setAttribute('aria-expanded','false');changed=true}if(changed){sync();menuToggle?.focus({preventScroll:true})}});addEventListener('pointerdown',()=>{d.dataset.inputModality='pointer'},{passive:true});document.addEventListener('click',sync);})();</script>`;return source.replace(/<\/body\s*>/i,`${js}</body>`)}
function byteLength(value){return new TextEncoder().encode(String(value||"")).length}function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:JSON_HEADERS})}
